"""Expand TSX_UNIVERSE to S&P/TSX Composite Index constituents.

One-shot script: scrapes the constituent list from Wikipedia, verifies
each ticker works in yfinance (batch download), and prints Python
snippets to paste into picker.py's TSX_UNIVERSE and STOCK_PROFILE.

Run again whenever the TSX Composite has rebalanced and you want to
catch new additions / drop departures.
"""
import io
import sys
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import requests
import yfinance as yf

import picker

# Wikipedia GICS labels -> picker sector names used in STOCK_PROFILE
SECTOR_MAP = {
    "Financials": "Financials",
    "Energy": "Energy",
    "Materials": "Materials",
    "Industrials": "Industrials",
    "Consumer Discretionary": "ConsumerDisc",
    "Consumer Staples": "ConsumerStaples",
    "Information Technology": "Technology",
    "Communication Services": "Communication",
    "Utilities": "Utilities",
    "Real Estate": "RealEstate",
    "Healthcare": "HealthCare",
}

print("[1] Fetching TSX Composite constituents from Wikipedia...")
r = requests.get("https://en.wikipedia.org/wiki/S%26P/TSX_Composite_Index",
                 headers={"User-Agent": "Mozilla/5.0"})
r.raise_for_status()
df = pd.read_html(io.StringIO(r.text))[3]
df.columns = ["ticker", "company", "sector", "industry"]
# Drop rows where ticker is NaN or non-string (Wikipedia table sometimes
# includes blank header rows between sector groupings).
df = df[df["ticker"].apply(lambda v: bool(isinstance(v, str) and v.strip()))].copy()
print(f"    {len(df)} constituents listed")

existing = set(picker.TSX_UNIVERSE)
print(f"    {len(existing)} already in TSX_UNIVERSE")

# Build candidate variants: most tickers are <BASE>.TO, but trusts use
# -UN.TO and some dual-class shares use -A.TO/-B.TO. Try the obvious
# form first, then known special patterns.
def candidates_for(base):
    """Generate yfinance ticker candidates for a Wikipedia-formatted base.

    Wikipedia uses '.' to separate share-class suffixes (CTC.A, AP.UN);
    yfinance uses '-' (CTC-A.TO, AP-UN.TO). Try the hyphen form first
    when the wiki base contains a dot; fall back to the literal form.
    """
    base = base.strip().upper()
    if "." in base:
        return [base.replace(".", "-") + ".TO", base + ".TO"]
    return [base + ".TO"]

all_candidates = []
candidate_to_row = {}
for _, row in df.iterrows():
    for c in candidates_for(row["ticker"]):
        if c in existing:
            continue
        if c not in candidate_to_row:
            all_candidates.append(c)
            candidate_to_row[c] = row

print(f"\n[2] Batch-downloading {len(all_candidates)} candidates from yfinance...")
data = yf.download(all_candidates, period="5d", progress=False, threads=True,
                   group_by="ticker", auto_adjust=True)

resolved = {}  # base ticker (from wiki) -> chosen variant
for _, row in df.iterrows():
    base = row["ticker"].strip().upper()
    for c in candidates_for(base):
        if c in existing:
            resolved[base] = c
            break
        try:
            sub = data[c]
            if sub is not None and not sub.dropna(how="all").empty:
                resolved[base] = c
                break
        except (KeyError, TypeError):
            continue

new_tickers = []
unresolved = []
for _, row in df.iterrows():
    base = row["ticker"].strip().upper()
    ticker = resolved.get(base)
    if ticker is None:
        unresolved.append(base)
        continue
    if ticker in existing:
        continue
    sector = SECTOR_MAP.get(row["sector"], row["sector"])
    new_tickers.append((ticker, sector, row["company"]))

print(f"    resolved: {len(resolved)}, new: {len(new_tickers)}, "
      f"unresolved: {len(unresolved)}")
if unresolved:
    print(f"    (unresolved tickers - verify manually): {unresolved}")

print(f"\n[3] Writing tsx_extended.py with {len(new_tickers)} additions...")
by_sector = {}
for t, s, c in new_tickers:
    by_sector.setdefault(s, []).append((t, c))

lines = [
    '"""TSX Composite constituents not in picker.TSX_UNIVERSE.',
    "",
    "Regenerated by expand_universe.py from Wikipedia's S&P/TSX Composite",
    "Index page. picker.py imports and merges these on module load.",
    "",
    "All entries default to style='core', sub_type='other' — concentration",
    "limits (max_per_style, max_per_type) still apply via those buckets.",
    "Refine specific entries by hand if you want a ticker to escape a",
    "particular bucket cap.",
    '"""',
    "",
    "EXTENDED_UNIVERSE = [",
]
for sector in sorted(by_sector):
    lines.append(f"    # {sector}")
    pairs = sorted(by_sector[sector])
    for i in range(0, len(pairs), 6):
        chunk = ", ".join(repr(t) for t, _ in pairs[i:i+6])
        lines.append(f"    {chunk},")
lines.append("]")
lines.append("")
lines.append("EXTENDED_PROFILES = {")
for t, s, company in sorted(new_tickers, key=lambda x: (x[1], x[0])):
    safe_company = company.replace('"', "'")[:50]
    lines.append(f'    "{t}": ("{s}", "core", "other"),  # {safe_company}')
lines.append("}")
lines.append("")

with open("tsx_extended.py", "w") as f:
    f.write("\n".join(lines))

print(f"    wrote tsx_extended.py ({len(new_tickers)} tickers across "
      f"{len(by_sector)} sectors)")
print(f"\nDone. Existing: {len(existing)}. After merge: "
      f"~{len(existing) + len(new_tickers)} tickers.")
