"""TSX Composite constituents not in picker.TSX_UNIVERSE.

Regenerated by expand_universe.py from Wikipedia's S&P/TSX Composite
Index page. picker.py imports and merges these on module load.

All entries default to style='core', sub_type='other' — concentration
limits (max_per_style, max_per_type) still apply via those buckets.
Refine specific entries by hand if you want a ticker to escape a
particular bucket cap.
"""

EXTENDED_UNIVERSE = [
    # Communication
    'CCA.TO', 'QBR-B.TO',
    # ConsumerDisc
    'DOO.TO', 'GIL.TO', 'NFI.TO', 'PET.TO', 'RCH.TO', 'TCL-A.TO',
    'WPK.TO',
    # ConsumerStaples
    'JWEL.TO', 'MRU.TO',
    # Energy
    'AAV.TO', 'ALA.TO', 'ATH.TO', 'BEP-UN.TO', 'BLX.TO', 'BTE.TO',
    'CCO.TO', 'CEU.TO', 'DML.TO', 'EFR.TO', 'GEI.TO', 'HWX.TO',
    'IPCO.TO', 'KEY.TO', 'NPI.TO', 'NXE.TO', 'POU.TO', 'PXT.TO',
    'SCR.TO', 'SOBO.TO', 'TOU.TO', 'TPZ.TO', 'TVK.TO', 'VET.TO',
    # Financials
    'BAM.TO', 'BN.TO', 'DFY.TO', 'GSY.TO', 'LB.TO', 'ONEX.TO',
    'SII.TO', 'TSU.TO', 'X.TO',
    # HealthCare
    'BHC.TO', 'CURA.TO', 'SIA.TO',
    # Industrials
    'AC.TO', 'ARE.TO', 'ATRL.TO', 'BBD-B.TO', 'BBUC.TO', 'BDGI.TO',
    'BDT.TO', 'CJT.TO', 'EFN.TO', 'EFX.TO', 'EIF.TO', 'FTT.TO',
    'MDA.TO', 'MTL.TO', 'RUS.TO', 'SES.TO', 'TRI.TO', 'WCN.TO',
    # Materials
    'AAUC.TO', 'ABRA.TO', 'AG.TO', 'ARIS.TO', 'ASM.TO', 'AYA.TO',
    'DPM.TO', 'DSV.TO', 'EDR.TO', 'EQX.TO', 'ERO.TO', 'FVI.TO',
    'GMIN.TO', 'IAU.TO', 'IMG.TO', 'KNT.TO', 'LAC.TO', 'LIF.TO',
    'LUG.TO', 'MAU.TO', 'MX.TO', 'NG.TO', 'NGEX.TO', 'NTR.TO',
    'OGC.TO', 'OLA.TO', 'PAAS.TO', 'PPTA.TO', 'SEA.TO', 'SJ.TO',
    'SKE.TO', 'SSRM.TO', 'SVM.TO', 'TFPM.TO', 'TKO.TO', 'TXG.TO',
    'USA.TO', 'VNP.TO', 'VZLA.TO', 'WDO.TO',
    # RealEstate
    'AIF.TO', 'BEI-UN.TO', 'CHP-UN.TO', 'CIGI.TO', 'CRR-UN.TO', 'CRT-UN.TO',
    'CSH-UN.TO', 'FCR-UN.TO', 'FSV.TO', 'IIP-UN.TO', 'KMP-UN.TO', 'PMZ-UN.TO',
    'SRU-UN.TO', 'VITL-UN.TO',
    # Technology
    'BB.TO', 'CLS.TO',
    # Utilities
    'ACO-X.TO', 'BIP-UN.TO', 'CPX.TO', 'SPB.TO', 'TA.TO',
]

EXTENDED_PROFILES = {
    "CCA.TO": ("Communication", "core", "other"),  # Cogeco Communications Inc.
    "QBR-B.TO": ("Communication", "core", "other"),  # Quebecor Inc.
    "DOO.TO": ("ConsumerDisc", "core", "other"),  # BRP Inc.
    "GIL.TO": ("ConsumerDisc", "core", "other"),  # Gildan Activewear Inc.
    "NFI.TO": ("ConsumerDisc", "core", "other"),  # NFI Group Inc.
    "PET.TO": ("ConsumerDisc", "core", "other"),  # Pet Valu Holdings Ltd.
    "RCH.TO": ("ConsumerDisc", "core", "other"),  # Richelieu Hardware Ltd.
    "TCL-A.TO": ("ConsumerDisc", "core", "other"),  # Transcontinental Inc.
    "WPK.TO": ("ConsumerDisc", "core", "other"),  # Winpak Ltd.
    "JWEL.TO": ("ConsumerStaples", "core", "other"),  # Jamieson Wellness Inc.
    "MRU.TO": ("ConsumerStaples", "core", "other"),  # Metro Inc.
    "AAV.TO": ("Energy", "core", "other"),  # Advantage Energy Ltd.
    "ALA.TO": ("Energy", "core", "other"),  # AltaGas Ltd.
    "ATH.TO": ("Energy", "core", "other"),  # Athabasca Oil Corporation
    "BEP-UN.TO": ("Energy", "core", "other"),  # Brookfield Renewable Partners L.P.
    "BLX.TO": ("Energy", "core", "other"),  # Boralex Inc.
    "BTE.TO": ("Energy", "core", "other"),  # Baytex Energy Corp.
    "CCO.TO": ("Energy", "core", "other"),  # Cameco Corporation
    "CEU.TO": ("Energy", "core", "other"),  # CES Energy Solutions Corp.
    "DML.TO": ("Energy", "core", "other"),  # Denison Mines Corp.
    "EFR.TO": ("Energy", "core", "other"),  # Energy Fuels Inc.
    "GEI.TO": ("Energy", "core", "other"),  # Gibson Energy Inc.
    "HWX.TO": ("Energy", "core", "other"),  # Headwater Exploration Inc.
    "IPCO.TO": ("Energy", "core", "other"),  # International Petroleum Corporation
    "KEY.TO": ("Energy", "core", "other"),  # Keyera Corp.
    "NPI.TO": ("Energy", "core", "other"),  # Northland Power Inc.
    "NXE.TO": ("Energy", "core", "other"),  # NexGen Energy Ltd.
    "POU.TO": ("Energy", "core", "other"),  # Paramount Resources Ltd.
    "PXT.TO": ("Energy", "core", "other"),  # Parex Resources Inc.
    "SCR.TO": ("Energy", "core", "other"),  # Strathcona Resources Ltd.
    "SOBO.TO": ("Energy", "core", "other"),  # South Bow Corporation
    "TOU.TO": ("Energy", "core", "other"),  # Tourmaline Oil Corp.
    "TPZ.TO": ("Energy", "core", "other"),  # Topaz Energy Corp.
    "TVK.TO": ("Energy", "core", "other"),  # TerraVest Industries Inc.
    "VET.TO": ("Energy", "core", "other"),  # Vermilion Energy Inc.
    "BAM.TO": ("Financials", "core", "other"),  # Brookfield Asset Management Ltd.
    "BN.TO": ("Financials", "core", "other"),  # Brookfield Corporation
    "DFY.TO": ("Financials", "core", "other"),  # Definity Financial Corporation
    "GSY.TO": ("Financials", "core", "other"),  # goeasy Ltd.
    "LB.TO": ("Financials", "core", "other"),  # Laurentian Bank of Canada
    "ONEX.TO": ("Financials", "core", "other"),  # Onex Corporation
    "SII.TO": ("Financials", "core", "other"),  # Sprott Inc.
    "TSU.TO": ("Financials", "core", "other"),  # Trisura Group Ltd.
    "X.TO": ("Financials", "core", "other"),  # TMX Group Limited
    "BHC.TO": ("HealthCare", "core", "other"),  # Bausch Health Companies Inc.
    "CURA.TO": ("HealthCare", "core", "other"),  # Curaleaf Holdings, Inc.
    "SIA.TO": ("HealthCare", "core", "other"),  # Sienna Senior Living Inc.
    "AC.TO": ("Industrials", "core", "other"),  # Air Canada
    "ARE.TO": ("Industrials", "core", "other"),  # Aecon Group Inc.
    "ATRL.TO": ("Industrials", "core", "other"),  # AtkinsRéalis Group Inc.
    "BBD-B.TO": ("Industrials", "core", "other"),  # Bombardier Inc.
    "BBUC.TO": ("Industrials", "core", "other"),  # Brookfield Business Corporation
    "BDGI.TO": ("Industrials", "core", "other"),  # Badger Infrastructure Solutions Ltd.
    "BDT.TO": ("Industrials", "core", "other"),  # Bird Construction Inc.
    "CJT.TO": ("Industrials", "core", "other"),  # Cargojet Inc.
    "EFN.TO": ("Industrials", "core", "other"),  # Element Fleet Management Corp.
    "EFX.TO": ("Industrials", "core", "other"),  # Equifax Inc.
    "EIF.TO": ("Industrials", "core", "other"),  # Exchange Income Corporation
    "FTT.TO": ("Industrials", "core", "other"),  # Finning International Inc.
    "MDA.TO": ("Industrials", "core", "other"),  # MDA Space Ltd.
    "MTL.TO": ("Industrials", "core", "other"),  # Mullen Group Ltd.
    "RUS.TO": ("Industrials", "core", "other"),  # Russel Metals Inc.
    "SES.TO": ("Industrials", "core", "other"),  # Secure Energy Services Inc.
    "TRI.TO": ("Industrials", "core", "other"),  # Thomson Reuters Corporation
    "WCN.TO": ("Industrials", "core", "other"),  # Waste Connections Inc.
    "AAUC.TO": ("Materials", "core", "other"),  # Allied Gold Corporation
    "ABRA.TO": ("Materials", "core", "other"),  # AbraSilver Resource Corp.
    "AG.TO": ("Materials", "core", "other"),  # First Majestic Silver Corp.
    "ARIS.TO": ("Materials", "core", "other"),  # Aris Mining Corporation
    "ASM.TO": ("Materials", "core", "other"),  # Avino Silver & Gold Mines Ltd.
    "AYA.TO": ("Materials", "core", "other"),  # Aya Gold & Silver Inc.
    "DPM.TO": ("Materials", "core", "other"),  # Dundee Precious Metals Inc.
    "DSV.TO": ("Materials", "core", "other"),  # Discovery Silver Corp.
    "EDR.TO": ("Materials", "core", "other"),  # Endeavour Silver Corp.
    "EQX.TO": ("Materials", "core", "other"),  # Equinox Gold Corp.
    "ERO.TO": ("Materials", "core", "other"),  # Ero Copper Corp.
    "FVI.TO": ("Materials", "core", "other"),  # Fortuna Mining Corp.
    "GMIN.TO": ("Materials", "core", "other"),  # G Mining Ventures Corp.
    "IAU.TO": ("Materials", "core", "other"),  # I-80 Gold Corp.
    "IMG.TO": ("Materials", "core", "other"),  # Iamgold Corporation
    "KNT.TO": ("Materials", "core", "other"),  # K92 Mining Inc.
    "LAC.TO": ("Materials", "core", "other"),  # Lithium Americas Corp.
    "LIF.TO": ("Materials", "core", "other"),  # Labrador Iron Ore Royalty Corporation
    "LUG.TO": ("Materials", "core", "other"),  # Lundin Gold Inc.
    "MAU.TO": ("Materials", "core", "other"),  # Montage Gold Corp.
    "MX.TO": ("Materials", "core", "other"),  # Methanex Corporation
    "NG.TO": ("Materials", "core", "other"),  # NovaGold Resources Inc.
    "NGEX.TO": ("Materials", "core", "other"),  # NGEx Minerals Ltd.
    "NTR.TO": ("Materials", "core", "other"),  # Nutrien Ltd.
    "OGC.TO": ("Materials", "core", "other"),  # OceanaGold Corporation
    "OLA.TO": ("Materials", "core", "other"),  # Orla Mining Ltd.
    "PAAS.TO": ("Materials", "core", "other"),  # Pan American Silver Corp.
    "PPTA.TO": ("Materials", "core", "other"),  # Perpetua Resources Corp.
    "SEA.TO": ("Materials", "core", "other"),  # Seabridge Gold Inc.
    "SJ.TO": ("Materials", "core", "other"),  # Stella-Jones Inc.
    "SKE.TO": ("Materials", "core", "other"),  # Skeena Resources Limited
    "SSRM.TO": ("Materials", "core", "other"),  # SSR Mining Inc.
    "SVM.TO": ("Materials", "core", "other"),  # Silvercorp Metals Inc.
    "TFPM.TO": ("Materials", "core", "other"),  # Triple Flag Precious Metals Corp.
    "TKO.TO": ("Materials", "core", "other"),  # Taseko Mines Limited
    "TXG.TO": ("Materials", "core", "other"),  # Torex Gold Resources Inc.
    "USA.TO": ("Materials", "core", "other"),  # Americas Gold And Silver Corporation
    "VNP.TO": ("Materials", "core", "other"),  # 5N Plus Inc.
    "VZLA.TO": ("Materials", "core", "other"),  # Vizsla Silver Corp.
    "WDO.TO": ("Materials", "core", "other"),  # Wesdome Gold Mines Ltd.
    "AIF.TO": ("RealEstate", "core", "other"),  # Altus Group Limited
    "BEI-UN.TO": ("RealEstate", "core", "other"),  # Boardwalk Real Estate Investment Trust
    "CHP-UN.TO": ("RealEstate", "core", "other"),  # Choice Properties Real Estate Investment Trust
    "CIGI.TO": ("RealEstate", "core", "other"),  # Colliers International Group Inc.
    "CRR-UN.TO": ("RealEstate", "core", "other"),  # Crombie Real Estate Investment Trust
    "CRT-UN.TO": ("RealEstate", "core", "other"),  # CT Real Estate Investment Trust
    "CSH-UN.TO": ("RealEstate", "core", "other"),  # Chartwell Retirement Residences
    "FCR-UN.TO": ("RealEstate", "core", "other"),  # First Capital Real Estate Investment Trust
    "FSV.TO": ("RealEstate", "core", "other"),  # FirstService Corporation
    "IIP-UN.TO": ("RealEstate", "core", "other"),  # InterRent Real Estate Investment Trust
    "KMP-UN.TO": ("RealEstate", "core", "other"),  # Killam Apartment Real Estate Investment Trust
    "PMZ-UN.TO": ("RealEstate", "core", "other"),  # Primaris Real Estate Investment Trust
    "SRU-UN.TO": ("RealEstate", "core", "other"),  # SmartCentres Real Estate Investment Trust
    "VITL-UN.TO": ("RealEstate", "core", "other"),  # Vital Infrastructure Property Trust.
    "BB.TO": ("Technology", "core", "other"),  # BlackBerry Limited
    "CLS.TO": ("Technology", "core", "other"),  # Celestica Inc.
    "ACO-X.TO": ("Utilities", "core", "other"),  # ATCO Ltd.
    "BIP-UN.TO": ("Utilities", "core", "other"),  # Brookfield Infrastructure Partners L.P.
    "CPX.TO": ("Utilities", "core", "other"),  # Capital Power Corporation
    "SPB.TO": ("Utilities", "core", "other"),  # Superior Plus Corp.
    "TA.TO": ("Utilities", "core", "other"),  # TransAlta Corporation
}
